<?php
declare(strict_types=1);
require_once __DIR__ . '/../admin-auth.php';
require_admin();

$id = (int) ($_GET['id'] ?? 0);
$product = ['name'=>'', 'description'=>'', 'standard'=>'', 'subject'=>'', 'publisher'=>'', 'isbn'=>'', 'price'=>'', 'discount_percent'=>'0', 'stock'=>'0', 'category_id'=>'', 'image_url'=>''];
if ($id) { $query = db()->prepare('SELECT * FROM products WHERE id=?'); $query->execute([$id]); $product = $query->fetch() ?: $product; }
$categories = db()->query('SELECT * FROM categories ORDER BY name')->fetchAll();
$message = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    check_csrf();
    $data = [trim($_POST['name'] ?? ''), trim($_POST['description'] ?? ''), trim($_POST['standard'] ?? ''), trim($_POST['subject'] ?? ''), trim($_POST['publisher'] ?? ''), trim($_POST['isbn'] ?? ''), (float) ($_POST['price'] ?? 0), (float) ($_POST['discount_percent'] ?? 0), max(0, (int) ($_POST['stock'] ?? 0)), (int) ($_POST['category_id'] ?? 0) ?: null, trim($_POST['image_url'] ?? '')];
    if ($data[0] === '' || $data[6] <= 0) { $message = 'Name and positive price are required.'; }
    elseif ($id) { $data[] = $id; db()->prepare('UPDATE products SET name=?,description=?,standard=?,subject=?,publisher=?,isbn=?,price=?,discount_percent=?,stock=?,category_id=?,image_url=? WHERE id=?')->execute($data); header('Location: products.php'); exit; }
    else { $slug = trim(preg_replace('/[^a-z0-9]+/i', '-', strtolower($data[0])), '-') . '-' . time(); db()->prepare('INSERT INTO products (name,slug,description,standard,subject,publisher,isbn,price,discount_percent,stock,category_id,image_url) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$data[0], $slug, $data[1], $data[2], $data[3], $data[4], $data[5], $data[6], $data[7], $data[8], $data[9], $data[10]]); header('Location: products.php'); exit; }
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Product Form</title><link rel="stylesheet" href="../style.css"><script src="../app.js" defer></script></head><body><main class="page-shell"><section class="form-card"><h1><?= $id ? 'Edit' : 'Add' ?> product</h1><?php if ($message): ?><p class="alert"><?= htmlspecialchars($message) ?></p><?php endif; ?><form method="post"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><label>Name<input name="name" value="<?= htmlspecialchars($product['name']) ?>" required></label><label>Description<textarea name="description" required><?= htmlspecialchars($product['description']) ?></textarea></label><label>Category<select name="category_id"><option value="">Select</option><?php foreach ($categories as $category): ?><option value="<?= $category['id'] ?>" <?= $product['category_id'] == $category['id'] ? 'selected' : '' ?>><?= htmlspecialchars($category['name']) ?></option><?php endforeach; ?></select></label><label>Standard<input name="standard" value="<?= htmlspecialchars($product['standard']) ?>"></label><label>Subject<input name="subject" value="<?= htmlspecialchars($product['subject']) ?>"></label><label>Publisher<input name="publisher" value="<?= htmlspecialchars($product['publisher']) ?>"></label><label>ISBN<input name="isbn" value="<?= htmlspecialchars($product['isbn']) ?>"></label><label>Image URL<input name="image_url" value="<?= htmlspecialchars($product['image_url']) ?>"></label><label>Price<input type="number" step="0.01" name="price" value="<?= htmlspecialchars((string) $product['price']) ?>" required></label><label>Discount %<input type="number" step="0.01" name="discount_percent" value="<?= htmlspecialchars((string) $product['discount_percent']) ?>"></label><label>Stock<input type="number" name="stock" value="<?= htmlspecialchars((string) $product['stock']) ?>"></label><button>Save product</button></form><p class="meta"><a href="products.php">Back</a></p></section></main></body></html>
